urls:
  https://saratov.cian.ru/cat.php?deal_type=rent&engine_version=2&offer_type=flat&region=4969&sort=creation_date_desc&type=4,
  https://www.avito.ru/saratov/kvartiry/sdam/na_dlitelnyy_srok-ASgBAgICAkSSA8gQ8AeQUg?s=104
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/shouse
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

telegram:
  token: 6211351016:AAFHx5QcDBjtabSP_0nOnXQiPMNYVp7nfU4
  username: "SearchHouse_TGBot"

jwt:
  jwtExpirationMs: 86400000
  refreshTokenExpirationMsec: 7776000000
  accessTokenCookieName: accessToken
  refreshTokenCookieName: refreshToken
server:
  port: 8088

upload:
  path: /Users/arinanikitina/IdeaProjects/search.house/src/main/resources/assets