urls:
  https://saratov.cian.ru/cat.php?deal_type=rent&engine_version=2&offer_type=flat&region=4969&sort=creation_date_desc&type=4,
  https://www.avito.ru/saratov/kvartiry/sdam/na_dlitelnyy_srok-ASgBAgICAkSSA8gQ8AeQUg?s=104